= XO Server Deployed, Configured, and Updated by Ansible
:icons: font

== Overview

This playbook will deploy, configure, and update an https://vates.tech/xen-orchestra/[XO Server] to manage the https://vates.tech/xcp-ng/[xcp-ng] servers.  
If you would like to know more about the XO Server and xcp-ng servers,  please visit the https://vates.tech/[Vates website].

== Plays in the Playbook

The playbook contains the following plays:

* `install` - Installs the XO Server as a service
* `update` - Pulls the latest code from GitHub and updates the XO Server

NOTE: The `update` play is in development.



=== Tested Servers

This playbook has been tested on the following servers:

* fedora 40 server

CAUTION: This playbook targets nvm for the users that is running the playbook and used to login to the server.


NOTE: NVM has to be installed for the root user as that is the user that will building and running the XO server.


== `install` Play Usage

The `install` play will install the XO Server as a service.
It will do this by doing the following things:

* Update the hostname of the server based on the value that is passed from the inventory file.
* Install dependencies for the XO Server per the https://xen-orchestra.com/docs/installation.html#from-the-sources[XO documentation] and make sure that firewalld is installed.
* Configure the firewall to allow the XO Server to be accessed on port 443. footnote:[It will also open the firewall to allow port 80 and redirect to port 443.]
* Install nvm and the latest LTS version of node. footnote:[NVM has to be installed for the root user as that is the user that will building and running the XO server.]
* Copy the configuration file to the `/etc/xo-server` directory and update as needed.
* Create a service file for the XO Server and start the service.

=== Variables

|===
| Variable Name | Description | Default Value

| install_nvm_version
| What version of nvm to install.
| v0.40.1

| install_nvm_script_location
| Where to download the nvm script and run it on the target XO Server.
| /tmp

| install_xo_location
| Location to install the XO Server code.
| /opt/xen-orchestra

| install_cert_file
| Location of the TLS certificate file.
| /etc/pki/xo-server/cert.pem

| install_key_file
| Location of the TLS key file. footnote:[The key file should be owned by the root user and have the permissions set to 600.]
| /etc/pki/xo-server/key.pem

|===
